### ISSUE TITLE
Dates generated by getFormattedDate method are not accepted

### ISSUE THREAD

**Issue by aonurozcan** [Modulr-finance/modulr-hmac#40]
Java version: 17

The following method produces a date which is considered invalid.

https://github.com/Modulr-finance/modulr-hmac/blob/3940d8a4d8b8560a2999678257d19171a3eecc37/samples/java/src/main/java/com/modulr/api/ModulrApiAuth.java#L98

**Example:**
Fri, 01 **Sept** 2023 13:36:44 GMT

"Sept" is not accepted, it should be "Sep" according to your requirements.

**Comment by elekdavid** [comment]
Same for the Kotlin example

https://github.com/Modulr-finance/modulr-hmac/blob/3940d8a4d8b8560a2999678257d19171a3eecc37/samples/kotlin/src/main/kotlin/com/modulr/api/Signature.kt#L47
