### ISSUE TITLE
Bring Java example inline with NodeJS

### ISSUE THREAD

**Issue by ngfgrant** [Modulr-finance/modulr-hmac#9]
## CONTEXT

The Java example code differs from the Node code in that it requires the `API_KEY` and `SECRET` to be passed in the constructor, whereas the node example reads from environment variable. My preference would be that any config is read in from the environment. Is it worth updating the Java example? Happy to help.

**Comment by riteshtendulkar** [comment]
Thanks for the comment. 

The reason Java example requires it to be passed in the constructor is that this can be then used in more flexible way. It can be used / called from a piece of code that picks these values from environment or from unit test case or indeed some other mechanism. The code focuses on demonstrating how to use the signature mechanism without making any assumptions about how it would get this config. 

Point taken about the samples not being inline ( as they were submitted by different developers ) . I have now updated the nodejs sample to be inline with Java
